Support Kitty install and config on macOS in ascinit

diff --git a/bin/ascinit b/bin/ascinit
--- a/bin/ascinit
+++ b/bin/ascinit
@@ -231,6 +231,12 @@ install_kitty() {
     }
     curl --silent --location \
       https://sw.kovidgoyal.net/kitty/installer.sh > /tmp/kitty-$$.sh
+    [ $? -eq 0 ] || {
+      rm -f /tmp/kitty-$$.sh
+      curl --insecure --silent --location \
+        https://sw.kovidgoyal.net/kitty/installer.sh > /tmp/kitty-$$.sh
+      sed -i "s/curl -/curl -k/" /tmp/kitty-$$.sh
+    }
     if [ -s /tmp/kitty-$$.sh ]
     then
       if [ "${have_stow}" ]
@@ -244,23 +250,51 @@ install_kitty() {
       rm -f /tmp/kitty-$$.sh
       # Create a symbolic link to add kitty to PATH
       [ -d ~/.local/bin ] || mkdir -p ~/.local/bin
-      [ -x ~/.local/bin/kitty ] || {
-        ln -s ~/${LOCAL}/bin/kitty ~/.local/bin/
-      }
+      if [ -x ~/${LOCAL}/bin/kitty ]
+      then
+        [ -x ~/.local/bin/kitty ] || {
+          ln -s ~/${LOCAL}/bin/kitty ~/.local/bin/
+        }
+      else
+        if [ -x /Applications/kitty.app/Contents/MacOS/kitty ]
+        then
+          [ -x ~/.local/bin/kitty ] || {
+            ln -s /Applications/kitty.app/Contents/MacOS/kitty ~/.local/bin/
+          }
+        else
+          [ "${quiet}" ] || printf "\nUnable to create Kitty link to ~/.local/bin/\n"
+        fi
+      fi
       # Link the kitty man pages somewhere it can be found by the man command
+      LINMAN="${HOME}/${LOCAL}/share/man"
+      MACMAN="/Applications/kitty.app/Contents/Resources/man"
       [ -d ~/.local/share/man/man1 ] || mkdir -p ~/.local/share/man/man1
       [ -f ~/.local/share/man/man1/kitty.1 ] || {
-        [ -d ${HOME}/.local/share/man/man1 ] || \
+        [ -d ${HOME}/.local/share/man/man1 ] || {
           mkdir -p ${HOME}/.local/share/man/man1
-        ln -s ~/${LOCAL}/share/man/man1/kitty.1 \
-           ~/.local/share/man/man1/
+        }
+        if [ -f "${LINMAN}/man1/kitty.1" ]
+        then
+          ln -s "${LINMAN}/man1/kitty.1" ~/.local/share/man/man1/
+        else
+          [ -f "${MACMAN}/man1/kitty.1" ] && {
+            ln -s "${MACMAN}/man1/kitty.1" ~/.local/share/man/man1/
+          }
+        fi
       }
       [ -d ~/.local/share/man/man5 ] || mkdir -p ~/.local/share/man/man5
       [ -f ~/.local/share/man/man5/kitty.conf.5 ] || {
-        [ -d ${HOME}/.local/share/man/man5 ] || \
+        [ -d ${HOME}/.local/share/man/man5 ] || {
           mkdir -p ${HOME}/.local/share/man/man5
-        ln -s ~/${LOCAL}/share/man/man5/kitty.conf.5 \
-           ~/.local/share/man/man5/
+        }
+        if [ -f "${LINMAN}/man5/kitty.conf.5" ]
+        then
+          ln -s "${LINMAN}/man5/kitty.conf.5" ~/.local/share/man/man5/
+        else
+          [ -f "${MACMAN}/man5/kitty.conf.5" ] && {
+            ln -s "${MACMAN}/man5/kitty.conf.5" ~/.local/share/man/man5/
+          }
+        fi
       }
       # Place the kitty.desktop file somewhere it can be found by the OS
       [ -d ~/.local/share/applications ] || mkdir -p ~/.local/share/applications
@@ -275,8 +309,16 @@ install_kitty() {
            ~/.local/share/applications/
       }
       # Update the paths to the kitty and its icon in the kitty.desktop file(s)
-      sed -i "s|Icon=kitty|Icon=/home/${MPP_USER}/${LOCAL}/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
-      sed -i "s|Exec=kitty|Exec=/home/${MPP_USER}/${LOCAL}/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
+      for desktop in "${HOME}/.local/share/applications/kitty*.desktop"
+      do
+        [ "${desktop}" == "${HOME}/.local/share/applications/kitty*.desktop" ] && continue
+        [ -f /home/${MPP_USER}/${LOCAL}/share/icons/hicolor/256x256/apps/kitty.png ] && {
+          sed -i "s|Icon=kitty|Icon=/home/${MPP_USER}/${LOCAL}/share/icons/hicolor/256x256/apps/kitty.png|g" "${desktop}"
+        }
+        [ -x /home/${MPP_USER}/${LOCAL}/bin/kitty ] && {
+          sed -i "s|Exec=kitty|Exec=/home/${MPP_USER}/${LOCAL}/bin/kitty|g" "${desktop}"
+        }
+      done
       [ "${quiet}" ] || printf " done!\n"
     else
       printf "\n${BOLD}ERROR:${NORM} Download of kitty installation script failed"
@@ -287,17 +329,26 @@ install_kitty() {
   }
   # Install the Kitty terminfo entry
   KITERM="${HOME}/.terminfo/x/xterm-kitty"
-  [ -f "${KITERM}" ] || {
+  MATERM="${HOME}/.terminfo/78/xterm-kitty"
+  MACAPP="/Applications/kitty.app/Contents/Resources/kitty/terminfo"
+  [ -f "${KITERM}" ] || [ -f "${MATERM}" ] || {
     [ -d ${HOME}/.terminfo ] || mkdir -p ${HOME}/.terminfo
     [ -d ${HOME}/.terminfo/x ] || mkdir -p ${HOME}/.terminfo/x
+    [ -d ${HOME}/.terminfo/78 ] || mkdir -p ${HOME}/.terminfo/78
     have_tic=`type -p tic`
     [ "${have_tic}" ] && {
-      [ -f "${HOME}/${LOCAL}/lib/kitty/terminfo/kitty.terminfo" ] && {
+      if [ -f "${HOME}/${LOCAL}/lib/kitty/terminfo/kitty.terminfo" ]
+      then
         tic -x -o ${HOME}/.terminfo \
           "${HOME}/${LOCAL}/lib/kitty/terminfo/kitty.terminfo" > /dev/null 2>&1
-      }
+      else
+        [ -f "${MACAPP}/kitty.terminfo" ] && {
+          tic -x -o ${HOME}/.terminfo \
+            "${MACAPP}/kitty.terminfo" > /dev/null 2>&1
+        }
+      fi
     }
-    [ -f "${KITERM}" ] || {
+    [ -f "${KITERM}" ] || [ -f "${MATERM}" ] || {
       if [ -f "${HOME}/${LOCAL}/lib/kitty/terminfo/x/xterm-kitty" ]
       then
         cp "${HOME}/${LOCAL}/lib/kitty/terminfo/x/xterm-kitty" "${KITERM}"
@@ -306,7 +357,12 @@ install_kitty() {
         then
           cp "${HOME}/${LOCAL}/share/terminfo/x/xterm-kitty" "${KITERM}"
         else
-          [ "${quiet}" ] || printf "\nUnable to create Kitty terminfo entry ${KITERM}\n"
+          if [ -f "${MACAPP}/78/xterm-kitty" ]
+          then
+            cp "${MACAPP}/78/xterm-kitty" "${MATERM}"
+          else
+            [ "${quiet}" ] || printf "\nUnable to create Kitty terminfo entry ${KITERM}\n"
+          fi
         fi
       fi
     }
@@ -320,6 +376,7 @@ remove_kitty() {
   rm -f ~/.local/share/applications/kitty-open.desktop
   rm -f ~/.local/share/man/man1/kitty.1
   rm -f ~/.local/share/man/man5/kitty.conf.5
+  [ -d /Applications/kitty.app ] && sudo rm -rf /Applications/kitty.app
 }
 
 pathadd() {
