First pass at Kitty integration

diff --git a/bin/ascinit b/bin/ascinit
--- a/bin/ascinit
+++ b/bin/ascinit
@@ -4,6 +4,7 @@
 #
 # Terminal emulators optionally installed:
 #     gnome-terminal
+#     kitty
 #     tilix
 #     xfce4-terminal
 #     cool-retro-term
@@ -13,7 +14,7 @@ BOLD=$(tput bold)
 NORM=$(tput sgr0)
 
 usage() {
-  printf "\nUsage: ascinit [-a] [-c] [-d] [-m] [-M] [-n] [-N] [-q] [-t] [-u]"
+  printf "\nUsage: ascinit [-a] [-c] [-d] [-m] [-M] [-n] [-N] [-q] [-r] [-t] [-u]"
   printf "\nWhere:"
   printf "\n\t-a indicates do not ask to play an animation when done"
   printf "\n\t-c indicates console mode - no windowing system, headless config"
@@ -21,8 +22,9 @@ usage() {
   printf "\n\t-m indicates setup user Mutt configuration"
   printf "\n\t-M indicates setup both Mutt and NeoMutt configurations"
   printf "\n\t-n indicates setup user NeoMutt configuration"
-  printf "\n\t-N indicates setup neither Mutt or NeoMutt configuration"
+  printf "\n\t-N do not prompt for installation of additional terminal emulators"
   printf "\n\t-q indicates quiet mode"
+  printf "\n\t-r indicates remove service/package"
   printf "\n\t-t indicates authorize the Rainbow Stream app at Twitter"
   printf "\n\t-u indicates display this usage message and exit\n"
   exit 1
@@ -50,37 +52,19 @@ inst_pkg() {
 }
 
 ask_install() {
-  opt="$1"
-  nam="$2"
-  pkg="$3"
-  echo "The ${opt} option indicates configure ${nam} but ${nam} is not installed"
+  nam="$1"
+  pkg="$2"
+  echo "Attempting to configure ${nam} but ${nam} is not installed"
   echo "Would you like to install ${nam} at this time?"
   while true
   do
     read -p "Install ${nam} ? (y/n) " yn
     case $yn in
       [Yy]* )
-          case ${pkg} in
-            mutt)
-                use_mutt=1
-                ;;
-            neomutt)
-                sudo dnf copr enable flatcap/neomutt -y 2> /dev/null
-                use_neomutt=1
-                ;;
-          esac
           inst_pkg ${pkg}
           break
           ;;
       [Nn]* )
-          case ${pkg} in
-            mutt)
-                use_mutt=
-                ;;
-            neomutt)
-                use_neomutt=
-                ;;
-          esac
           break
           ;;
         * ) echo "Please answer yes or no."
@@ -89,9 +73,139 @@ ask_install() {
   done
 }
 
+install_kitty() {
+  have_kitty=`type -p kitty`
+  [ "${have_kitty}" ] || {
+    [ "${quiet}" ] || {
+      printf "\n\tInstalling Kitty terminal emulator ..."
+    }
+    curl --silent --location \
+      https://sw.kovidgoyal.net/kitty/installer.sh > /tmp/kitty-$$.sh
+    if [ -f /tmp/kitty-$$.sh ]
+    then
+      have_stow=`type -p stow`
+      if [ "${have_stow}" ]
+      then
+        sh /tmp/kitty-$$.sh launch=n dest=~/.local/stow > /dev/null 2>&1
+        cd ~/.local/stow
+        stow kitty.app
+        LOCAL=".local/stow"
+      else
+        sh /tmp/kitty-$$.sh launch=n > /dev/null 2>&1
+        LOCAL=".local"
+      fi
+      rm -f /tmp/kitty-$$.sh
+      # Create a symbolic link to add kitty to PATH
+      # (assuming ~/.local/bin is in your system-wide PATH)
+      [ -d ~/.local/bin ] || mkdir -p ~/.local/bin
+      [ -x ~/.local/bin/kitty ] || {
+        ln -s ~/${LOCAL}/kitty.app/bin/kitty ~/.local/bin/
+      }
+      # Link the kitty man pages somewhere it can be found by the man command
+      [ -d ~/.local/share/man/man1 ] || mkdir -p ~/.local/share/man/man1
+      [ -f ~/.local/share/man/man1/kitty.1 ] || {
+        [ -d ${HOME}/.local/share/man/man1 ] || \
+          mkdir -p ${HOME}/.local/share/man/man1
+        ln -s ~/${LOCAL}/kitty.app/share/man/man1/kitty.1 \
+           ~/.local/share/man/man1/
+      }
+      [ -d ~/.local/share/man/man5 ] || mkdir -p ~/.local/share/man/man5
+      [ -f ~/.local/share/man/man5/kitty.conf.5 ] || {
+        [ -d ${HOME}/.local/share/man/man5 ] || \
+          mkdir -p ${HOME}/.local/share/man/man5
+        ln -s ~/${LOCAL}/kitty.app/share/man/man5/kitty.conf.5 \
+           ~/.local/share/man/man5/
+      }
+      # Place the kitty.desktop file somewhere it can be found by the OS
+      [ -d ~/.local/share/applications ] || mkdir -p ~/.local/share/applications
+      [ -f ~/.local/share/applications/kitty.desktop ] || {
+        cp ~/${LOCAL}/kitty.app/share/applications/kitty.desktop \
+           ~/.local/share/applications/
+      }
+      # If you want to open text files and images in kitty via your file manager
+      # also add the kitty-open.desktop file
+      [ -f ~/.local/share/applications/kitty-open.desktop ] || {
+        cp ~/${LOCAL}/kitty.app/share/applications/kitty-open.desktop \
+           ~/.local/share/applications/
+      }
+      # Update the paths to the kitty and its icon in the kitty.desktop file(s)
+      sed -i "s|Icon=kitty|Icon=/home/${MPP_USER}/${LOCAL}/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
+      sed -i "s|Exec=kitty|Exec=/home/${MPP_USER}/${LOCAL}/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
+      [ "${quiet}" ] || printf " done!\n"
+    else
+      printf "\n${BOLD}ERROR:${NORM} Download of Kitty installation script failed"
+      printf "\nSee https://sw.kovidgoyal.net/kitty/binary/#manually-installing"
+      printf "\nto manually install the Kitty terminal emulator\n"
+    fi
+  }
+}
+
+remove_kitty() {
+  rm -rf ~/.local/kitty.app
+  rm -f ~/.local/bin/kitty
+  rm -f ~/.local/share/applications/kitty.desktop
+  rm -f ~/.local/share/applications/kitty-open.desktop
+  rm -f ~/.local/share/man/man1/kitty.1
+  rm -f ~/.local/share/man/man5/kitty.conf.5
+}
+
+# Clear the Bash cache so we know for sure if something is installed
+hash -r
+
+[ "$1" == "kitty" ] && {
+  [ "${remove}" ] && {
+    printf "\nRemoving Kitty terminal emulator.\n\n"
+    while true
+    do
+      read -p "Do you wish to continue with Kitty removal ? (y/n) " yn
+      case $yn in
+          [Yy]* )
+                break
+                ;;
+          [Nn]* )
+                printf "\nKitty removal aborted."
+                printf "\nExiting.\n\n"
+                exit 0
+                ;;
+              * ) echo "Please answer yes or no."
+                ;;
+      esac
+    done
+    remove_kitty
+    printf "\n${BOLD}Kitty removed${NORM}"
+    printf "\nTo re-install Kitty run ${BOLD}'ascinit kitty'${NORM}\n\n"
+    exit 0
+  }
+  [ "${quiet}" ] || {
+    printf "\nInstalling Kitty terminal emulator\n"
+  }
+  while true
+  do
+    read -p "Do you wish to continue with Kitty installation ? (y/n) " yn
+    case $yn in
+      [Yy]* )
+            break
+            ;;
+      [Nn]* )
+            printf "\nKitty installation aborted."
+            printf "\nExiting.\n\n"
+            exit 0
+            ;;
+          * ) echo "Please answer yes or no."
+            ;;
+    esac
+  done
+  install_kitty
+  [ "${quiet}" ] || {
+    printf "\n\n${BOLD}Kitty terminal emulator installed${NORM}\n"
+  }
+  exit 0
+}
+
 have_mutt=`type -p mutt`
 have_neomutt=`type -p neomutt`
 have_gnome=`type -p gnome-terminal`
+have_kitty=`type -p kitty`
 have_tilix=`type -p tilix`
 have_xfce4=`type -p xfce4-terminal`
 have_retro=`type -p cool-retro-term`
@@ -107,11 +221,11 @@ ask_anim=1
 console=
 debug=
 init_twit=
+inst_terms=1
 quiet=
-use_mutt=
-use_neomutt=1
+remove=
 
-while getopts "acdmMnNqtu" flag; do
+while getopts "acdmMNnqrtu" flag; do
   case $flag in
     a)
         ask_anim=
@@ -123,43 +237,23 @@ while getopts "acdmMnNqtu" flag; do
         debug=1
         ;;
     m)
-        if [ "${have_mutt}" ]
-        then
-          use_mutt=1
-          use_neomutt=
-        else
-          ask_install -m Mutt mutt
-        fi
+        [ "${have_mutt}" ] || ask_install Mutt mutt
         ;;
     n)
-        if [ "${have_neomutt}" ]
-        then
-          use_mutt=
-          use_neomutt=1
-        else
-          ask_install -n NeoMutt neomutt
-        fi
+        [ "${have_neomutt}" ] || ask_install NeoMutt neomutt
         ;;
     M)
-        if [ "${have_mutt}" ]
-        then
-          use_mutt=1
-        else
-          ask_install -M Mutt mutt
-        fi
-        if [ "${have_neomutt}" ]
-        then
-          use_neomutt=1
-        else
-          ask_install -M NeoMutt neomutt
-        fi
+        [ "${have_mutt}" ] || ask_install Mutt mutt
+        [ "${have_neomutt}" ] || ask_install NeoMutt neomutt
         ;;
     N)
-        use_mutt=
-        use_neomutt=
+        inst_terms=
         ;;
     q)
         quiet=1
+        ;;
+    r)
+        remove=1
         ;;
     t)
         init_twit=1
@@ -323,6 +417,23 @@ shift $(( OPTIND - 1 ))
     mkdir -p ${HOME}/.contacts/friends
   }
 }
+
+install_kitty
+KITTYCONFDIR="${HOME}/.config/kitty"
+KITTYCONF="${KITTYCONFDIR}/asciiville.conf"
+# Setup default kitty configuration for this user unless one exists
+[ "${quiet}" ] || {
+  printf "\n\tInstalling Kitty configuration in ${KITTYCONFDIR} ..."
+}
+# If there is no user kitty config folder then copy the
+# MusicPlayerPlus kitty config folder into the user's home
+if [ -d ${KITTYCONFDIR} ]
+then
+  cp -an ${CONFDIR}/kitty ${CONF}
+else
+  cp -a ${CONFDIR}/kitty ${KITTYCONFDIR}
+fi
+[ -f ${KITTYCONFDIR}/kitty.conf ] || cp ${KITTYCONF} ${KITTYCONFDIR}/kitty.conf
 
 # Setup default rifle configuration for this user unless one exists
 [ -f ${CONFDIR}/rifle.conf ] && {
@@ -601,59 +712,69 @@ create_new_profile() {
 }
 
 [ "${console}" ] || {
-  [ "${have_gnome}" ] || inst_pkg gnome-terminal
-  [ "${have_tilix}" ] || inst_pkg tilix
-  [ "${have_xfce4}" ] || inst_pkg xfce4-terminal
-  [ "${have_retro}" ] || inst_pkg cool-retro-term
-  # If no gnome-terminal Asciiville profile exists, create one
-  declare -a profiles
-  profile_name="Asciiville"
+  [ "${inst_terms}" ] && {
+    [ "${have_gnome}" ] || ask_install Gnome-Terminal gnome-terminal
+    [ "${have_tilix}" ] || ask_install Tilix tilix
+    [ "${have_xfce4}" ] || ask_install Xfce4-terminal xfce4-terminal
+    [ "${have_retro}" ] || ask_install Cool-Retro-Term cool-retro-term
+    have_gnome=`type -p gnome-terminal`
+    have_tilix=`type -p tilix`
+    have_xfce4=`type -p xfce4-terminal`
+    have_retro=`type -p cool-retro-term`
+  }
+  [ "${have_gnome}" ] && {
+    # If no gnome-terminal Asciiville profile exists, create one
+    declare -a profiles
+    profile_name="Asciiville"
 
-  profile_exists=
-  dconfdir=/org/gnome/terminal/legacy/profiles:
+    profile_exists=
+    dconfdir=/org/gnome/terminal/legacy/profiles:
 
-  # profiles=($(gconftool-2 -R $gconfdir | grep $gconfdir | cut -d/ -f5 |  \
-  #          cut -d: -f1))
-  profiles=($(gsettings get org.gnome.Terminal.ProfilesList list | tr -d "[]\',"))
+    # profiles=($(gconftool-2 -R $gconfdir | grep $gconfdir | cut -d/ -f5 |  \
+    #          cut -d: -f1))
+    profiles=($(gsettings get org.gnome.Terminal.ProfilesList list | tr -d "[]\',"))
 
-  if [ "$profiles" = "" ]
-  then
-    create_new_profile gnome ${profile_name}
-  else
-    for i in ${!profiles[*]}
-    do
-      visname="$(dconf read $dconfdir/:${profiles[i]}/visible-name)"
-      [ "${visname}" == "'${profile_name}'" ] && profile_exists=1
-      [ "$profile_exists" ] && break
-    done
-  fi
+    if [ "$profiles" = "" ]
+    then
+      create_new_profile gnome ${profile_name}
+    else
+      for i in ${!profiles[*]}
+      do
+        visname="$(dconf read $dconfdir/:${profiles[i]}/visible-name)"
+        [ "${visname}" == "'${profile_name}'" ] && profile_exists=1
+        [ "$profile_exists" ] && break
+      done
+    fi
 
-  [ "$profile_exists" ] || {
-    # Create an Asciiville profile in gnome-terminal for this user
-    create_new_profile gnome ${profile_name}
+    [ "$profile_exists" ] || {
+      # Create an Asciiville profile in gnome-terminal for this user
+      create_new_profile gnome ${profile_name}
+    }
   }
 
-  # Create Asciiville Tilix profile, similar to Gnome-terminal's
-  profile_exists=
-  dconfdir=/com/gexperts/Tilix/profiles
+  [ "${have_tilix}" ] && {
+    # Create Asciiville Tilix profile, similar to Gnome-terminal's
+    profile_exists=
+    dconfdir=/com/gexperts/Tilix/profiles
 
-  profiles=($(gsettings get com.gexperts.Tilix.ProfilesList list | tr -d "[]\',"))
+    profiles=($(gsettings get com.gexperts.Tilix.ProfilesList list | tr -d "[]\',"))
 
-  if [ "$profiles" = "" ]
-  then
-    create_new_profile tilix ${profile_name}
-  else
-    for i in ${!profiles[*]}
-    do
-      visname="$(dconf read $dconfdir/${profiles[i]}/visible-name)"
-      [ "${visname}" == "'${profile_name}'" ] && profile_exists=1
-      [ "$profile_exists" ] && break
-    done
-  fi
+    if [ "$profiles" = "" ]
+    then
+      create_new_profile tilix ${profile_name}
+    else
+      for i in ${!profiles[*]}
+      do
+        visname="$(dconf read $dconfdir/${profiles[i]}/visible-name)"
+        [ "${visname}" == "'${profile_name}'" ] && profile_exists=1
+        [ "$profile_exists" ] && break
+      done
+    fi
 
-  [ "$profile_exists" ] || {
-    # Create an Asciiville profile in Tilix for this user
-    create_new_profile tilix ${profile_name}
+    [ "$profile_exists" ] || {
+      # Create an Asciiville profile in Tilix for this user
+      create_new_profile tilix ${profile_name}
+    }
   }
 }
 
@@ -707,7 +828,6 @@ CONF="${HOME}/.config/asciiville/config"
   echo "COMMAND=btop" >> ${CONF}
   echo "FULLSCREEN=" >> ${CONF}
   echo "MTITLE=\"Btop++ System Monitor\"" >> ${CONF}
-  have_gnome=`type -p gnome-terminal`
   if [ "${have_gnome}" ]
   then
     echo "CURRENT=" >> ${CONF}
diff --git a/bin/termprofset b/bin/termprofset
--- a/bin/termprofset
+++ b/bin/termprofset
@@ -4,6 +4,7 @@
 #               or XFCE4 terminal font settings
 #
 # Written May, 2020 by Ronald Record <ronaldrecord@gmail.com>
+# Modified Aug, 2022 by Ronald Record to add Kitty support
 #
 # From https://ncona.com/2019/11/configuring-gnome-terminal-programmatically/
 #
@@ -18,6 +19,7 @@
 CONF_DIR="${HOME}/.config"
 SAVE_DIR="${CONF_DIR}/asciiville"
 SAVE_GNOME="${SAVE_DIR}/gnome"
+SAVE_KITTY="${SAVE_DIR}/kitty"
 SAVE_TILIX="${SAVE_DIR}/tilix"
 SAVE_XFCE4="${SAVE_DIR}/xfce4"
 RC="${CONF_DIR}/xfce4/terminal/terminalrc"
@@ -31,7 +33,8 @@ TILIX_PATH="/com/gexperts/Tilix/profiles/"
 TILIX_LIST="com.gexperts.Tilix.ProfilesList"
 
 usage() {
-  printf "\nUsage: termprofset [-f fontname] [-s fontsize] [-p profile] [-glBRStxu]"
+  printf "\nUsage: termprofset [-f fontname] [-s fontsize] [-p profile]"
+  printf "\n\t[-K socket] [-gklBRStxu]"
   printf "\nWhere:"
   printf "\n\t-B indicates set background to black, no transparency"
   printf "\n\t-f 'fontname' specifies the font name to set terminal's font to"
@@ -40,11 +43,13 @@ usage() {
   printf "\n\t-R indicates restore original saved settings and exit"
   printf "\n\t-S indicates save original settings"
   printf "\n\t-g indicates use Gnome terminal emulator"
+  printf "\n\t-k indicates use Kitty terminal emulator"
+  printf "\n\t-K 'socket' specifies the Kitty control socket name"
   printf "\n\t-l indicates list current profile settings and exit"
   printf "\n\t-t indicates use Tilix terminal emulator"
   printf "\n\t-x indicates use Xfce4 terminal emulator"
   printf "\n\t-u displays this usage message and exits"
-  printf "\n\nDefault terminal emulator is Gnome"
+  printf "\n\nDefault terminal emulator is Kitty"
   printf "\nDefault terminal profile is Asciiville"
   printf "\nDefault font is Monospace"
   printf "\nDefault font size is 4\n"
@@ -57,23 +62,37 @@ PROF_NAME="Asciiville"
 SET_BLACK=
 SAVE_ORIG=
 REST_ORIG=
-USE_GNOME=1
-TERM_NAME=Gnome
+TERM_NAME=Kitty
+USE_KITTY=1
+USE_GNOME=
 USE_TILIX=
 USE_XFCE4=
 SHOW_LIST=
-while getopts "Bgf:lp:Rs:Stxu" flag; do
+KITTY_SOCKET="/tmp/asckitty"
+while getopts "Bgf:kK:lp:Rs:Stxu" flag; do
   case $flag in
     B)
       SET_BLACK=1
       ;;
     g)
+      USE_KITTY=
       USE_TILIX=
       USE_XFCE4=
       USE_GNOME=1
+      TERM_NAME=Gnome
       ;;
     f)
       FONT_NAME="${OPTARG}"
+      ;;
+    K)
+      KITTY_SOCKET="${OPTARG}"
+      ;;
+    k)
+      USE_TILIX=
+      USE_GNOME=
+      USE_KITTY=1
+      USE_XFCE4=
+      TERM_NAME=Kitty
       ;;
     l)
       SHOW_LIST=1
@@ -93,10 +112,12 @@ while getopts "Bgf:lp:Rs:Stxu" flag; do
     t)
       USE_TILIX=1
       USE_GNOME=
+      USE_KITTY=
       USE_XFCE4=
       TERM_NAME=Tilix
       ;;
     x)
+      USE_KITTY=
       USE_TILIX=
       USE_GNOME=
       USE_XFCE4=1
@@ -109,176 +130,220 @@ while getopts "Bgf:lp:Rs:Stxu" flag; do
 done
 
 # Which terminal are we using?
-if [ "${USE_GNOME}" ]
+if [ "${USE_KITTY}" ]
 then
-  T_PROF="${GNOME_PROF}"
-  T_PATH="${GNOME_PATH}"
-  T_LIST="${GNOME_LIST}"
-  T_SAVE="${SAVE_GNOME}"
+  T_PROF=
+  T_PATH=
+  T_LIST=
+  T_SAVE="${SAVE_KITTY}"
 else
-  if [ "${USE_TILIX}" ]
+  if [ "${USE_GNOME}" ]
   then
-    T_PROF="${TILIX_PROF}"
-    T_PATH="${TILIX_PATH}"
-    T_LIST="${TILIX_LIST}"
-    T_SAVE="${SAVE_TILIX}"
+    T_PROF="${GNOME_PROF}"
+    T_PATH="${GNOME_PATH}"
+    T_LIST="${GNOME_LIST}"
+    T_SAVE="${SAVE_GNOME}"
   else
-    if [ "${USE_XFCE4}" ]
+    if [ "${USE_TILIX}" ]
     then
-      T_PROF=
-      T_PATH=
-      T_LIST=
-      T_SAVE="${SAVE_XFCE4}"
-      have_set_xfce4=`type -p set_xfce_font`
-      have_set_trans=`type -p set_xfce_trans`
+      T_PROF="${TILIX_PROF}"
+      T_PATH="${TILIX_PATH}"
+      T_LIST="${TILIX_LIST}"
+      T_SAVE="${SAVE_TILIX}"
     else
-      echo "Unknown/Unsupported terminal emulator. Exiting."
-      usage
+      if [ "${USE_XFCE4}" ]
+      then
+        T_PROF=
+        T_PATH=
+        T_LIST=
+        T_SAVE="${SAVE_XFCE4}"
+        have_set_xfce4=`type -p set_xfce_font`
+        have_set_trans=`type -p set_xfce_trans`
+      else
+        echo "Unknown/Unsupported terminal emulator. Exiting."
+        usage
+      fi
     fi
   fi
 fi
 
 # Restore the saved original terminal settings and exit
 [ "${REST_ORIG}" ] && {
-  if [ "${USE_XFCE4}" ]
+  if [ "${USE_KITTY}" ]
   then
-    [ -f "${T_SAVE}" ] && cp "${T_SAVE}" "${RC}"
+    # Restore settings
+    kitty @ --to unix:${KITTY_SOCKET} set-font-size 0
+    kitty @ --to unix:${KITTY_SOCKET} set-colors --reset
   else
-    [ -f "${T_SAVE}" ] && {
-      . "${T_SAVE}"
-      gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
-                font "${current_font}"
-      gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
-                use-system-font ${use_system_font}
-      gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
-                use-theme-colors ${use_theme}
-      gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
-                background-color "${background}"
-      gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
-                foreground-color "${foreground}"
-    }
+    if [ "${USE_XFCE4}" ]
+    then
+      [ -f "${T_SAVE}" ] && cp "${T_SAVE}" "${RC}"
+    else
+      [ -f "${T_SAVE}" ] && {
+        . "${T_SAVE}"
+        gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
+                  font "${current_font}"
+        gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
+                  use-system-font ${use_system_font}
+        gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
+                  use-theme-colors ${use_theme}
+        gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
+                  background-color "${background}"
+        gsettings set ${T_PROF}:${T_PATH}:${TERM_PROF}/ \
+                  foreground-color "${foreground}"
+      }
+    fi
   fi
   exit 0
 }
 
-if [ "${USE_XFCE4}" ]
+if [ "${USE_KITTY}" ]
 then
+  # Get the current font and settings
+  # kitty @ --to unix:${KITTY_SOCKET} get-colors [options] ...
+  # kitty @ --to unix:${KITTY_SOCKET} set-colors --reset
   [ "${SHOW_LIST}" ] && {
-    echo "Current font settings for ${TERM_NAME}:"
-    [ "${have_set_xfce4}" ] && set_xfce_font
+    echo "Don't know how to get current font settings for ${TERM_NAME}"
     exit 0
   }
 else
-  # Get the current font, settings, and profile id
-  TERM_PROF=
-  if [ "${PROF_NAME}" == "default" ]
+  if [ "${USE_XFCE4}" ]
   then
-    TERM_PROF=`gsettings get ${T_LIST} default | awk -F \' '{print $2}'`
+    [ "${SHOW_LIST}" ] && {
+      echo "Current font settings for ${TERM_NAME}:"
+      [ "${have_set_xfce4}" ] && set_xfce_font
+      exit 0
+    }
   else
-    profiles=($(gsettings get ${T_LIST} list | tr -d "[]\',"))
-    if [ "$profiles" = "" ]
+    # Get the current font, settings, and profile id
+    TERM_PROF=
+    if [ "${PROF_NAME}" == "default" ]
     then
-      echo "No profiles detected. Exiting."
-      usage
+      TERM_PROF=`gsettings get ${T_LIST} default | awk -F \' '{print $2}'`
     else
-      if [ "${USE_GNOME}" ]
+      profiles=($(gsettings get ${T_LIST} list | tr -d "[]\',"))
+      if [ "$profiles" = "" ]
       then
-        P_PATH="${T_PATH}:"
+        echo "No profiles detected. Exiting."
+        usage
       else
-        P_PATH="${T_PATH}"
+        if [ "${USE_GNOME}" ]
+        then
+          P_PATH="${T_PATH}:"
+        else
+          P_PATH="${T_PATH}"
+        fi
+        for i in ${!profiles[*]}
+        do
+          visname="$(dconf read ${P_PATH}${profiles[i]}/visible-name)"
+          [ "${visname}" == "'${PROF_NAME}'" ] && {
+            TERM_PROF="${profiles[i]}"
+            break
+          }
+        done
       fi
-      for i in ${!profiles[*]}
-      do
-        visname="$(dconf read ${P_PATH}${profiles[i]}/visible-name)"
-        [ "${visname}" == "'${PROF_NAME}'" ] && {
-          TERM_PROF="${profiles[i]}"
-          break
-        }
-      done
+      [ "${TERM_PROF}" ] || {
+        echo "Could not locate ${PROF_NAME} profile. Exiting."
+        usage
+      }
     fi
-    [ "${TERM_PROF}" ] || {
-      echo "Could not locate ${PROF_NAME} profile. Exiting."
-      usage
+    #
+    USE_SYSTEM_FONT=`gsettings get \
+        ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-system-font`
+    CURR_FONT=`gsettings get \
+        ${T_PROF}:${T_PATH}:${TERM_PROF}/ font`
+    USE_THEME=`gsettings get \
+        ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-theme-colors`
+    USE_BACK=`gsettings get \
+        ${T_PROF}:${T_PATH}:${TERM_PROF}/ background-color`
+    USE_FORE=`gsettings get \
+        ${T_PROF}:${T_PATH}:${TERM_PROF}/ foreground-color`
+    [ "${SHOW_LIST}" ] && {
+      echo "Current settings for ${PROF_NAME} profile in ${TERM_NAME}:"
+      echo "font=${CURR_FONT}"
+      echo "use-system-font=${USE_SYSTEM_FONT}"
+      echo "use-theme-colors=${USE_THEME}"
+      echo "background-color=${USE_BACK}"
+      echo "foreground-color=${USE_FORE}"
+      exit 0
     }
   fi
-  #
-  USE_SYSTEM_FONT=`gsettings get \
-      ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-system-font`
-  CURR_FONT=`gsettings get \
-      ${T_PROF}:${T_PATH}:${TERM_PROF}/ font`
-  USE_THEME=`gsettings get \
-      ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-theme-colors`
-  USE_BACK=`gsettings get \
-      ${T_PROF}:${T_PATH}:${TERM_PROF}/ background-color`
-  USE_FORE=`gsettings get \
-      ${T_PROF}:${T_PATH}:${TERM_PROF}/ foreground-color`
-  [ "${SHOW_LIST}" ] && {
-    echo "Current settings for ${PROF_NAME} profile in ${TERM_NAME}:"
-    echo "font=${CURR_FONT}"
-    echo "use-system-font=${USE_SYSTEM_FONT}"
-    echo "use-theme-colors=${USE_THEME}"
-    echo "background-color=${USE_BACK}"
-    echo "foreground-color=${USE_FORE}"
-    exit 0
-  }
 fi
 
 # Save the current terminal settings
 [ "${SAVE_ORIG}" ] && {
   [ -d "${CONF_DIR}" ] || mkdir "${CONF_DIR}"
   [ -d "${SAVE_DIR}" ] || mkdir "${SAVE_DIR}"
-  if [ "${USE_XFCE4}" ]
+  if [ "${USE_KITTY}" ]
   then
-    [ -f "${RC}" ] && cp "${RC}" "${T_SAVE}"
-  else
-    echo "TERM_PROF=\"${TERM_PROF}\"" > ${T_SAVE}
-    echo "current_font=\"${CURR_FONT}\"" >> ${T_SAVE}
-    echo "use_system_font=${USE_SYSTEM_FONT}" >> ${T_SAVE}
-    echo "use_theme=${USE_THEME}" >> ${T_SAVE}
-    echo "background=\"${USE_BACK}\"" >> ${T_SAVE}
-    echo "foreground=\"${USE_FORE}\"" >> ${T_SAVE}
-  fi
-}
-
-#
-# Finally, we can use gsettings to change the properties we care about.
-#
-if [ "${USE_GNOME}" ]
-then
-  gsettings set \
-    ${T_PROF}:${T_PATH}:${TERM_PROF}/ font "'${FONT_NAME} ${FONT_SIZE}'"
-  gsettings set \
-    ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-system-font false
-  gsettings set \
-    ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-theme-colors false
-  gsettings set \
-    ${T_PROF}:${T_PATH}:${TERM_PROF}/ background-color '#000000'
-  gsettings set \
-    ${T_PROF}:${T_PATH}:${TERM_PROF}/ foreground-color '#AFAFAF'
-else
-  if [ "${USE_TILIX}" ]
-  then
-    gsettings set \
-      ${T_PROF}:${T_PATH}${TERM_PROF}/ font "'${FONT_NAME} ${FONT_SIZE}'"
-    gsettings set \
-      ${T_PROF}:${T_PATH}${TERM_PROF}/ use-system-font false
-    gsettings set \
-      ${T_PROF}:${T_PATH}${TERM_PROF}/ use-theme-colors false
-    gsettings set \
-      ${T_PROF}:${T_PATH}${TERM_PROF}/ background-color '#000000'
-    gsettings set \
-      ${T_PROF}:${T_PATH}${TERM_PROF}/ foreground-color '#AFAFAF'
+    touch "${T_SAVE}"
   else
     if [ "${USE_XFCE4}" ]
     then
-      [ "${have_set_xfce4}" ] && set_xfce_font -f "${FONT_NAME}" -s ${FONT_SIZE}
-      # Set background to black, no transparency, and exit
-      [ "${SET_BLACK}" ] && {
-        [ "${have_set_trans}" ] && set_xfce_trans 1 black
-      }
+      [ -f "${RC}" ] && cp "${RC}" "${T_SAVE}"
     else
-      echo "Unknown/Unsupported terminal emulator. Exiting."
-      usage
+      echo "TERM_PROF=\"${TERM_PROF}\"" > ${T_SAVE}
+      echo "current_font=\"${CURR_FONT}\"" >> ${T_SAVE}
+      echo "use_system_font=${USE_SYSTEM_FONT}" >> ${T_SAVE}
+      echo "use_theme=${USE_THEME}" >> ${T_SAVE}
+      echo "background=\"${USE_BACK}\"" >> ${T_SAVE}
+      echo "foreground=\"${USE_FORE}\"" >> ${T_SAVE}
+    fi
+  fi
+}
+
+if [ "${USE_KITTY}" ]
+then
+  # Set the font name and size
+  kitty @ --to unix:${KITTY_SOCKET} set-font-size ${FONT_SIZE}
+  # Set background to black, no transparency
+  [ "${SET_BLACK}" ] && {
+    # 'dynamic_background_opacity' option in kitty.conf must be
+    # turned on to be able to set background opacity
+    kitty @ --to unix:${KITTY_SOCKET} set-background-opacity 1.0
+    kitty @ --to unix:${KITTY_SOCKET} set-colors background=black
+  }
+else
+  #
+  # With Gnome and Tilix use gsettings to change the properties we care about
+  #
+  if [ "${USE_GNOME}" ]
+  then
+    gsettings set \
+      ${T_PROF}:${T_PATH}:${TERM_PROF}/ font "'${FONT_NAME} ${FONT_SIZE}'"
+    gsettings set \
+      ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-system-font false
+    gsettings set \
+      ${T_PROF}:${T_PATH}:${TERM_PROF}/ use-theme-colors false
+    gsettings set \
+      ${T_PROF}:${T_PATH}:${TERM_PROF}/ background-color '#000000'
+    gsettings set \
+      ${T_PROF}:${T_PATH}:${TERM_PROF}/ foreground-color '#AFAFAF'
+  else
+    if [ "${USE_TILIX}" ]
+    then
+      gsettings set \
+        ${T_PROF}:${T_PATH}${TERM_PROF}/ font "'${FONT_NAME} ${FONT_SIZE}'"
+      gsettings set \
+        ${T_PROF}:${T_PATH}${TERM_PROF}/ use-system-font false
+      gsettings set \
+        ${T_PROF}:${T_PATH}${TERM_PROF}/ use-theme-colors false
+      gsettings set \
+        ${T_PROF}:${T_PATH}${TERM_PROF}/ background-color '#000000'
+      gsettings set \
+        ${T_PROF}:${T_PATH}${TERM_PROF}/ foreground-color '#AFAFAF'
+    else
+      if [ "${USE_XFCE4}" ]
+      then
+        [ "${have_set_xfce4}" ] && set_xfce_font -f "${FONT_NAME}" -s ${FONT_SIZE}
+        # Set background to black, no transparency, and exit
+        [ "${SET_BLACK}" ] && {
+          [ "${have_set_trans}" ] && set_xfce_trans 1 black
+        }
+      else
+        echo "Unknown/Unsupported terminal emulator. Exiting."
+        usage
+      fi
     fi
   fi
 fi
