Fix Python module installs in ascinit

diff --git a/bin/ascinit b/bin/ascinit
--- a/bin/ascinit
+++ b/bin/ascinit
@@ -17,6 +17,7 @@ fi
 MUSEDIR="${TOP}/asciiville/music"
 CONFDIR=${TOP}/share/asciiville
 USERCONF="${HOME}/.config"
+VENV_DIR="${HOME}/.venv"
 GHUC="https://raw.githubusercontent.com"
 OWNER=doctorfree
 BOLD=$(tput bold 2>/dev/null)
@@ -462,8 +463,13 @@ remove_kitty() {
 
 remove_durdraw() {
   [ -f ${HOME}/.venv/bin/activate ] && source ${HOME}/.venv/bin/activate
+  PYTHON=
+  set_python_path
+  [ "${PYTHON}" ] || {
+    printf "\nERROR: Python not found. Exiting.\n"
+    exit 1
+  }
   ${PYTHON} -m pip uninstall -y durdraw >/dev/null 2>&1
-  command -v deactivate && deactivate
   rm -rf ~/.local/share/durdraw
   rm -f ~/.local/bin/durdraw
   rm -f ~/.local/share/man/man1/durdraw.1
@@ -504,6 +510,20 @@ install_neovim() {
 pathadd() {
   if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
     export PATH="$1${PATH:+":$PATH"}"
+  fi
+}
+
+set_python_path() {
+  have_py3=$(type -p python3)
+  if [ "${have_py3}" ]; then
+    PYTHON=python3
+  else
+    have_py=$(type -p python)
+    if [ "${have_py}" ]; then
+      PYTHON=python
+    else
+      printf "\nWARNING: could not locate Python in PATH.\n"
+    fi
   fi
 }
 
@@ -616,24 +636,25 @@ fi
   fi
 }
 
-VENV_DIR="${HOME}/.venv"
 [ -f ${VENV_DIR}/bin/activate ] && source ${VENV_DIR}/bin/activate
 
-have_py3=$(type -p python3)
-if [ "${have_py3}" ]; then
-  PYTHON=python3
-else
-  have_py=$(type -p python)
-  if [ "${have_py}" ]; then
-    PYTHON=python
-  else
-    printf "\nWARNING: could not locate Python in PATH.\n"
-  fi
-fi
+PYTHON=
+set_python_path
+[ "${PYTHON}" ] || {
+  printf "\nERROR: Python not found. Exiting.\n"
+  exit 1
+}
 
 # Setup Python virtual environment
 [ -f ${VENV_DIR}/bin/activate ] || ${PYTHON} -m venv ${VENV_DIR}
 [ -f ${VENV_DIR}/bin/activate ] && source ${VENV_DIR}/bin/activate
+
+PYTHON=
+set_python_path
+[ "${PYTHON}" ] || {
+  printf "\nERROR: Python not found. Exiting.\n"
+  exit 1
+}
 
 # Upgrade pip, setuptools
 ${PYTHON} -m pip install --upgrade pip >/dev/null 2>&1
@@ -1444,27 +1465,12 @@ fi
   export HOMEBREW_NO_AUTO_UPDATE=1
 }
 
-# Brew doesn't create a python symlink so we do so here
-[ "${usebrew}" ] && {
-  install_package python
-  python3_path=$(command -v python3)
-  [ "${python3_path}" ] && {
-    python_dir=$(dirname ${python3_path})
-    if [ -w ${python_dir} ]; then
-      rm -f ${python_dir}/python
-      ln -s ${python_dir}/python3 ${python_dir}/python
-    else
-      sudo rm -f ${python_dir}/python
-      sudo ln -s ${python_dir}/python3 ${python_dir}/python
-    fi
-  }
-}
+[ -f ${VENV_DIR}/bin/activate ] && source ${VENV_DIR}/bin/activate
 
-PYTHON="python3"
-have_python3=$(type -p python3)
-[ "${have_python3}" ] || {
-  echo "[ERROR] Could not find python3 binary."
-  echo "Please add it to your \$PATH and rerun ascinit."
+PYTHON=
+set_python_path
+[ "${PYTHON}" ] || {
+  printf "\nERROR: Python not found. Exiting.\n"
   exit 1
 }
 
@@ -1489,6 +1495,11 @@ have_pip=$(type -p pip3)
   [ "${quiet}" ] || {
     printf " done"
   }
+}
+
+# Need portaudio on macOS for pyaudio wheel
+[ "${usebrew}" ] && [ "${have_brew}" ] && {
+  brew install --quiet portaudio >/dev/null 2>&1
 }
 
 for pkg in setuptools asciimatics ddgr socli future wheel \
