Batch ascii art files for display, separate specified ascii art command line arguments with a comma when passing to show_ascii_art

diff --git a/bin/show_ascii_art b/bin/show_ascii_art
--- a/bin/show_ascii_art
+++ b/bin/show_ascii_art
@@ -13,7 +13,7 @@ ALTSONG="${MUSEDIR}/Epic_Dramatic-Yuriy_Bespalov.wav"
 LOLCAT_NORM="lolcat"
 LOLCAT_ANIM="lolcat --animate --speed=60.0"
 LOLCAT="${LOLCAT_ANIM}"
-art="yinyang"
+artfiles="Friends/tux,Friends/yinyang"
 custom_song=
 art_font_size=4
 txt_font_size=20
@@ -34,14 +34,16 @@ longchars="...^,:;Ili+_-1tfjrxnuvczXYUJCLQ0OZmwqpdbkhaoMW8"
 set -m
 
 usage() {
-  printf "\nUsage: show_ascii_art [-a art] [-A art_dir] [-b] [-B] [-c] [-C]"
+  printf "\nUsage: show_ascii_art [-a art[,art2,...]] [-A art_dir] [-b] [-B] [-c] [-C]"
   printf "\n\t[-d font_dir] [-D seconds] [-e term] [-F large_font] [-f small_font]"
   printf "\n\t[-g] [-i image] [-I input_dir] [-O output_dir] [-K fifo_name] [-l level]"
   printf "\n\t[-L] [-n tabs] [-N depth] [-o] [-p palette] [-P] [-q] [-r]"
   printf "\n\t[-s show] [-S song] [-t first_text] [-T second_text]"
   printf "\n\t[-h height] [-w width] [-v] [-z] [-u]"
   printf "\nWhere:"
-  printf "\n\t-a 'art' specifies which ascii art to display"
+  printf "\n\t-a 'art' specifies ascii art file(s) to display"
+  printf "\n\t\tmultiple files are separated by a comma with no spaces"
+  printf "\n\t\t(e.g. '-a Friends/tux,Doctorwhen/Capitola_Village_Vivid')"
   printf "\n\t\t'art' can be the relative path to a file in:"
   printf "\n\t\t\t${ARTDIR}"
   printf "\n\t\tor the path to a file, with or without file extension"
@@ -249,7 +251,7 @@ have_jp2a=`type -p jp2a`
 while getopts "a:A:bBcCD:d:e:gh:i:I:K:l:LF:f:n:N:oO:Pp:qrs:S:t:T:vw:zu" flag; do
   case $flag in
       a)
-          art="${OPTARG}"
+          artfiles="${OPTARG}"
           ;;
       A)
           ARTDIR="${OPTARG}"
@@ -800,46 +802,50 @@ then
   show_ascii "/tmp/${image_name}$$.asc" "${tabs}"
 else
   tput civis -- invisible
-  if [ -f "${ARTDIR}/${art}.asc" ]
-  then
-    show_ascii "${ARTDIR}/${art}.asc" "${tabs}"
-  else
-    if [ -f "${ARTDIR}/${art}.asc.gz" ]
+  IFS=',' read -r -a artarray <<< "${artfiles}"
+  for art in "${artarray[@]}"
+  do
+    if [ -f "${ARTDIR}/${art}.asc" ]
     then
-      show_ascii "${ARTDIR}/${art}.asc.gz" "${tabs}"
+      show_ascii "${ARTDIR}/${art}.asc" "${tabs}"
     else
-      if [ -f "${ARTDIR}/${art}" ]
+      if [ -f "${ARTDIR}/${art}.asc.gz" ]
       then
-        show_ascii "${ARTDIR}/${art}" "${tabs}"
+        show_ascii "${ARTDIR}/${art}.asc.gz" "${tabs}"
       else
-        if [ -f "${art}.asc" ]
+        if [ -f "${ARTDIR}/${art}" ]
         then
-          show_ascii "${art}.asc" "${tabs}"
+          show_ascii "${ARTDIR}/${art}" "${tabs}"
         else
-          if [ -f "${art}.asc.gz" ]
+          if [ -f "${art}.asc" ]
           then
-            show_ascii "${art}.asc.gz" "${tabs}"
+            show_ascii "${art}.asc" "${tabs}"
           else
-            if [ -f "${art}" ]
+            if [ -f "${art}.asc.gz" ]
             then
-              show_ascii "${art}" "${tabs}"
+              show_ascii "${art}.asc.gz" "${tabs}"
             else
-              foundit=
-              for asc in "${ARTDIR}/*/${art}*"
-              do
-                [ "${asc}" == "${ARTDIR}/*/${art}*" ] && continue 
-                [ -f "${asc}" ] && {
-                  foundit=1
-                  show_ascii "${asc}" "${tabs}"
-                }
-              done
-              [ "${foundit}" ] || echo "Cannot locate ${art}"
+              if [ -f "${art}" ]
+              then
+                show_ascii "${art}" "${tabs}"
+              else
+                foundit=
+                for asc in "${ARTDIR}/*/${art}*"
+                do
+                  [ "${asc}" == "${ARTDIR}/*/${art}*" ] && continue 
+                  [ -f "${asc}" ] && {
+                    foundit=1
+                    show_ascii "${asc}" "${tabs}"
+                  }
+                done
+                [ "${foundit}" ] || echo "Cannot locate ${art}"
+              fi
             fi
           fi
         fi
       fi
     fi
-  fi
+  done
 fi
 
 [ -f "/tmp/${image_name}$$.asc" ] && {
