Add color display option to show_endo

diff --git a/bin/show_endo b/bin/show_endo
--- a/bin/show_endo
+++ b/bin/show_endo
@@ -5,6 +5,8 @@ ENDO=${ENDO_DIR}/endoh1
 ESRC=${ENDO_DIR}/endoh1.c
 #ALL=("clock.txt" "column.txt" "column2.txt" "column3.txt" "corners.txt" "dripping-pan.txt" "evaporation.txt" "flat.txt" "fountain.txt" "funnel.txt" "funnel2.txt" "funnel3.txt" "glass-half-empty.txt" "leidenfrost.txt" "logo.txt" "pour-out.txt" "tanada.txt")
 ALL=("column.txt" "logo.txt" "pour-out.txt" "tanada.txt")
+BOLD=$(tput bold)
+NORM=$(tput sgr0)
 
 [ -x ${ENDO} ] || {
   echo "${ENDO} not found or not executable"
@@ -15,16 +17,23 @@ set +m
 
 clear
 echo ""
-echo "The 'endoh1' entry won honorable mention in the 2012 International"
-echo "Obfuscated C Code contest. This entry's source code when viewed"
-echo "appears to be the word 'Fluid' in a container. When compiled it"
-echo "can take its own source code as input and it displays an ascii"
-echo "character animation of fluid in a heated container. The simulation"
-echo "utilizes the 'Smoothed-particle hydrodynamics' method to model"
-echo "properties of fluid dynamics."
-echo ""
+printf "\n\tThe entry written by Yusuke Endoh won honorable mention in the\n"
+printf "\n\t\t${BOLD} 2012 International Obfuscated C Code Contest${NORM}"
+printf "\n\t\t       https://www.ioccc.org/index.html\n"
+printf "\n\tThe entry's source code when viewed appears to be the word"
+printf "\n\t'Fluid' in a container. When compiled it can take its own"
+printf "\n\tsource code as input to display an ascii character animation"
+printf "\n\tof a simulation of fluid dynamics in a container.\n"
+printf "\n\tThe simulation uses 'Smoothed-particle hydrodynamics'"
+printf "\n\tto model properties of fluid dynamics in a container.\n"
+printf "\n\tWhen prompted, respond with one of the following:"
+printf "\n\t\t'c' for a color simulation"
+printf "\n\t\t'y' for a monochrome simulation (the entry)"
+printf "\n\t\t'n' to exit the display of simulations"
+printf "\n\tDuring a simulation use 'Ctrl-c' to start a new simulation or exit"
+printf "\n\n\t"
 
-read -p "Press Enter to view the program source code" yn
+read -p "Press Enter to view the program source code: " yn
 
 clear
 echo ""
@@ -39,27 +48,33 @@ next_input() {
     while true
     do
       clear
-      read -p "View another ASCII fluid dynamics animation ('n' to exit)? (y/n) " yn
+      # Seed random generator
+      RANDOM=$$$(date +%s)
+      INPUT=${ALL[ $RANDOM % ${#ALL[@]} ]}
+      ESRC=${ENDO_DIR}/${INPUT}
+      delete=("${INPUT}")
+      for target in "${delete[@]}"; do
+        for i in "${!ALL[@]}"; do
+          if [[ ${ALL[i]} = $target ]]; then
+            unset 'ALL[i]'
+          fi
+        done
+      done
+      new_array=()
+      for i in "${!ALL[@]}"; do
+        new_array+=( "${ALL[i]}" )
+      done
+      ALL=("${new_array[@]}")
+      unset new_array
+      read -p "View another ASCII fluid dynamics simulation ('n' to exit)? (c/y/n) [y] " yn
+      yn=${yn:-y}
       case $yn in
+        [Cc]* )
+            ENDO=${ENDO_DIR}/endoh1_color
+            break
+            ;;
         [Yy]* )
-            # Seed random generator
-            RANDOM=$$$(date +%s)
-            INPUT=${ALL[ $RANDOM % ${#ALL[@]} ]}
-            ESRC=${ENDO_DIR}/${INPUT}
-            delete=("${INPUT}")
-            for target in "${delete[@]}"; do
-              for i in "${!ALL[@]}"; do
-                if [[ ${ALL[i]} = $target ]]; then
-                  unset 'ALL[i]'
-                fi
-              done
-            done
-            new_array=()
-            for i in "${!ALL[@]}"; do
-              new_array+=( "${ALL[i]}" )
-            done
-            ALL=("${new_array[@]}")
-            unset new_array
+            ENDO=${ENDO_DIR}/endoh1
             break
             ;;
         [Nn]* )
@@ -73,37 +88,42 @@ next_input() {
   fi
 }
 
+cols=`tput cols`
+lines=`tput lines`
+[ ${cols} -ge 80 ] && [ ${lines} -ge 24 ] || {
+  echo "The ASCII fluid dynamics simulations requires a terminal window"
+  echo "of size 80x24 or greater. This terminal window appears to be ${cols}x${lines}"
+  echo ""
+  echo "Resize the terminal window and run this command again"
+  exit 1
+}
+
+echo ""
+read -p "View the animated ASCII fluid dynamics simulation ? (c/y/n) [y] " yn
+yn=${yn:-y}
+case $yn in
+  [Cc]* )
+        ENDO=${ENDO_DIR}/endoh1_color
+        break
+        ;;
+  [Yy]* )
+        ENDO=${ENDO_DIR}/endoh1
+        break
+        ;;
+  [Nn]* )
+        clear
+        exit 0
+        ;;
+      * ) echo "Please answer 'color', 'yes' or 'no'."
+        ;;
+esac
+
 trap 'next_input' SIGINT
 
 while true
 do
-  echo "During an animation use 'Ctrl-c' to start a new animation"
-  read -p "View the ASCII fluid dynamics animations ? (y/n) " yn
-  case $yn in
-    [Yy]* )
-          cols=`tput cols`
-          lines=`tput lines`
-          [ ${cols} -gt 80 ] && [ ${lines} -gt 25 ] || {
-            echo "The ASCII fluid dynamics animation requires a terminal window"
-            echo "of size greater than 80x25"
-            echo ""
-            echo "Resize the terminal window and run this command again"
-            exit 1
-          }
-          while true
-          do
-            clear
-            ${ENDO} < ${ESRC}
-          done
-          break
-          ;;
-    [Nn]* )
-          clear
-          exit 0
-          ;;
-        * ) echo "Please answer yes or no."
-          ;;
-  esac
+  clear
+  ${ENDO} < ${ESRC}
 done
 
 clear
