Do not assume project is cloned in HOME/src/Asciiville

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -11,10 +11,8 @@
 # sudo dpkg -i "${PKG}"
 # sudo apt-get install -f
 
-SRC_NAME="Asciiville"
 PKG_NAMES="Asciiville"
 APT_NAMES="asciiville"
-SRC="${HOME}/src"
 DEB_ARCH=amd64
 RPM_ARCH=x86_64
 BOLD=$(tput bold)
@@ -23,20 +21,22 @@ NORMAL=$(tput sgr0)
 PKG_AVAILABLE=
 PKG_SELECTED=
 
-[ -f "${SRC}/${SRC_NAME}/VERSION" ] || {
-  echo "Missing VERSION file: ${SRC}/${SRC_NAME}/VERSION"
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+
+[ -f "${SCRIPT_DIR}/VERSION" ] || {
+  echo "Missing VERSION file: ${SCRIPT_DIR}/VERSION"
   echo "Exiting"
   exit 1
 }
 
-. "${SRC}/${SRC_NAME}/VERSION"
+. "${SCRIPT_DIR}/VERSION"
 PKG_VER=${VERSION}
 PKG_REL=${RELEASE}
 
 get_available_packages() {
-  for pkgs in ${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.${SUF}
+  for pkgs in ${SCRIPT_DIR}/releases/${PKG_VER}/*.${SUF}
   do
-    [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.${SUF}" ] || {
+    [ "${pkgs}" == "${SCRIPT_DIR}/releases/${PKG_VER}/*.${SUF}" ] || {
       for pkg in ${pkgs}
       do
         pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF}//"` 
@@ -149,12 +149,12 @@ get_available_packages
 
 for PKG_NAME in ${PKG_NAMES}
 do
-  PKG="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF}"
+  PKG="${SCRIPT_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF}"
   [ -f "${PKG}" ] || {
     echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF} not found."
-    for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
+    for pkgs in ${SCRIPT_DIR}/releases/*/${PKG_NAME}_*.${SUF}
     do
-      [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
+      [ "${pkgs}" == "${SCRIPT_DIR}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
         echo "Found existing packages:"
         echo "${pkgs}"
       }
