Add support for manual removal of components

diff --git a/Uninstall b/Uninstall
--- a/Uninstall
+++ b/Uninstall
@@ -1,65 +1,18 @@
 #!/bin/bash
 
+PKGS="neomutt cmatrix figlet lolcat mplayer neomutt newsboat ranger tmux w3m asciinema speedtest-cli neofetch imagemagick gnupg"
+PYMS="asciimatics ddgr rainbowstream socli future xtermcolor ffmpeg-python pyaudio term-image"
+PROJECTS="asciiville-aewan btop cbftp any2ascii endoh1"
+
 ALL=
 [ "$1" == "all" ] && ALL=1
 
 export PATH=${PATH}:/usr/local/bin:/snap/bin
 plat=`uname -s`
+
 if [ "$plat" == "Darwin" ]
 then
-    sudo pkg/Uninstall-bin.sh
-    [ "${ALL}" ] && {
-      have_brew=`type -p brew`
-      if [ "${have_brew}" ]
-      then
-        PKGS="neomutt btop cmatrix figlet lolcat mplayer neomutt newsboat ranger tmux w3m asciinema speedtest-cli neofetch imagemagick gnupg"
-        PYMS="asciimatics ddgr rainbowstream socli future xtermcolor ffmpeg-python pyaudio term-image"
-        echo "The 'all' argument indicates uninstall all Asciiville components."
-        echo "This will attempt to uninstall the following packages:"
-        echo ""
-        echo "${PKGS}"
-        echo ""
-        echo "And the following Python modules:"
-        echo ""
-        echo "${PYMS}"
-        echo ""
-        echo "Do you wish to proceed with removal of these modules and packages?"
-        while true
-        do
-          read -p "Uninstall Asciiville components ? (y/n) " yn
-          case $yn in
-            [Yy]* )
-                break
-                ;;
-            [Nn]* )
-                exit 0
-                ;;
-              * ) echo "Please answer yes or no."
-                ;;
-          esac
-        done
-        for pkg in ${PKGS}
-        do
-          brew list -q ${pkg} > /dev/null 2>&1
-          [ $? -eq 0 ] && brew uninstall -q ${pkg}
-        done
-        python3_inst=`type -p python3`
-        if [ "${python3_inst}" ]
-        then
-          PYTHON="python3"
-        else
-          PYTHON="python"
-        fi
-        for mod in ${PYMS}
-        do
-          pip list | grep ${mod} > /dev/null && {
-            ${PYTHON} -m pip uninstall ${mod} -y
-          }
-        done
-      else
-        echo "Brew not found. Asciiville components not removed."
-      fi
-    }
+    sudo pkg/Uninstall-bin.sh $1
 else
   debian=
   have_apt=`type -p apt`
@@ -75,18 +28,18 @@ else
     echo "${ID_LIKE}" | grep debian > /dev/null && debian=1
   }
 
-  PKG=asciiville
-  [ "${debian}" ] || [ "${arch}" ] || PKG=Asciiville
+  ASCPKG=asciiville
+  [ "${debian}" ] || [ "${arch}" ] || ASCPKG=Asciiville
 
   if [ "${debian}" ]
   then
     if [ "${have_apt}" ]
     then
-      sudo apt remove "${PKG}" -y
+      sudo apt remove "${ASCPKG}" -y
     else
       if [ "${have_dpkg}" ]
       then
-        sudo dpkg -r "${PKG}"
+        sudo dpkg -r "${ASCPKG}"
       else
         echo "Cannot locate apt or dpkg to remove. Skipping."
       fi
@@ -96,18 +49,18 @@ else
     then
       if [ "${have_pac}" ]
       then
-        sudo pacman -Rs "${PKG}"
+        sudo pacman -Rs "${ASCPKG}"
       else
         echo "Cannot locate pacman to remove. Skipping."
       fi
     else
       if [ "${have_dnf}" ]
       then
-        sudo dnf remove "${PKG}"
+        sudo dnf remove "${ASCPKG}"
       else
         if [ "${have_rpm}" ]
         then
-          sudo rpm -e "${PKG}"
+          sudo rpm -e "${ASCPKG}"
         else
           echo "Cannot locate either dnf or rpm to remove. Skipping."
         fi
@@ -115,3 +68,98 @@ else
     fi
   fi
 fi
+
+[ "${ALL}" ] && {
+  echo "The 'all' argument indicates uninstall all Asciiville components."
+  echo "This will attempt to uninstall the following packages:"
+  echo ""
+  echo "${PKGS}"
+  echo ""
+  echo "And the following Python modules:"
+  echo ""
+  echo "${PYMS}"
+  echo ""
+  echo "Note that this may remove packages installed prior to Asciiville."
+  echo "You may have to re-install those packages."
+  echo ""
+  echo "Do you wish to proceed with removal of these modules and packages?"
+  while true
+  do
+    read -p "Uninstall Asciiville components ? (y/n) " yn
+    case $yn in
+      [Yy]* )
+          break
+          ;;
+      [Nn]* )
+          exit 0
+          ;;
+        * ) echo "Please answer yes or no."
+          ;;
+    esac
+  done
+  python3_inst=`type -p python3`
+  if [ "${python3_inst}" ]
+  then
+    PYTHON="python3"
+  else
+    PYTHON="python"
+  fi
+  if [ "$plat" == "Darwin" ]
+  then
+    have_brew=`type -p brew`
+    if [ "${have_brew}" ]
+    then
+      PKGS="btop ${PKGS}"
+      for pkg in ${PKGS}
+      do
+        brew list -q ${pkg} > /dev/null 2>&1
+        [ $? -eq 0 ] && brew uninstall -q ${pkg}
+      done
+    else
+      echo "Brew not found. Asciiville components not removed."
+    fi
+  else
+    if [ "${debian}" ]
+    then
+      if [ "${have_apt}" ]
+      then
+        sudo apt remove "${PKGS}" -y
+      else
+        if [ "${have_dpkg}" ]
+        then
+          sudo dpkg -r "${PKGS}"
+        else
+          echo "Cannot locate apt or dpkg to remove. Skipping."
+        fi
+      fi
+    else
+      if [ "${arch}" ]
+      then
+        if [ "${have_pac}" ]
+        then
+          sudo pacman -Rs "${PKGS}"
+        else
+          echo "Cannot locate pacman to remove. Skipping."
+        fi
+      else
+        if [ "${have_dnf}" ]
+        then
+          sudo dnf remove "${PKGS}"
+        else
+          if [ "${have_rpm}" ]
+          then
+            sudo rpm -e "${PKGS}"
+          else
+            echo "Cannot locate either dnf or rpm to remove. Skipping."
+          fi
+        fi
+      fi
+    fi
+  fi
+  for mod in ${PYMS}
+  do
+    pip list | grep ${mod} > /dev/null && {
+      ${PYTHON} -m pip uninstall ${mod} -y
+    }
+  done
+}
