Install pip modules during postinst, add Twitter client

diff --git a/pkg/debian/postinst b/pkg/debian/postinst
--- a/pkg/debian/postinst
+++ b/pkg/debian/postinst
@@ -1,5 +1,39 @@
-#!/bin/sh
+#!/bin/bash
+# postinst script for rooncommandline
+#
+# see: dh_installdeb(1)
+
 set -e
-if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
-	update-menus
-fi
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+        python3 -m pip install asciimatics
+        python3 -m pip install rainbowstream
+        [ -x "`which update-menus 2>/dev/null`" ]; then
+            update-menus
+        fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+exit 0
